# Generated by Django 2.2.5 on 2019-09-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('date', models.DateTimeField(verbose_name='date planned')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('loc_type', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField(verbose_name='start time of event')),
                ('end_time', models.DateTimeField(verbose_name='end time of event')),
                ('cost', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Plan')),
            ],
        ),
    ]
