# Generated by Django 2.2.5 on 2019-11-26 23:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Where would you like to search?')),
                ('loc_type', models.CharField(blank=True, choices=[('restaurants', 'restaurants'), ('bars', 'bars'), ('arts & entertainment', 'arts & entertainment')], max_length=100, null=True, verbose_name='Location Type')),
                ('loc_category', models.CharField(blank=True, choices=[('0', '--------'), ('1', 'empty')], max_length=100, null=True, verbose_name='Location Category')),
                ('price', models.CharField(blank=True, choices=[('', 'Choose a price level'), ('1', '$'), ('2', '$$'), ('3', '$$$')], default='', max_length=1, null=True)),
                ('min_rating', models.CharField(blank=True, choices=[('', 'Choose a minimum rating'), ('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], max_length=1, null=True, verbose_name='Minimum Rating')),
                ('transportation', models.CharField(blank=True, choices=[('1', 'Walk'), ('2', 'Car'), ('3', 'Both')], max_length=1, null=True, verbose_name='Mode of Transportation')),
                ('result_count', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Number of Search Results')),
                ('start_time', models.TimeField(blank=True, default='12:00', null=True, verbose_name='Start Time of Event')),
                ('end_time', models.TimeField(blank=True, default='12:30', null=True, verbose_name='End Time of Event')),
                ('search_radius', models.FloatField(default=5, verbose_name='Search Radius(in miles)')),
                ('lat_coord', models.DecimalField(decimal_places=6, default=40.002287, max_digits=9)),
                ('long_coord', models.DecimalField(decimal_places=6, default=-83.016017, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date planned')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=30, verbose_name='Name of Location')),
                ('loc_type', models.CharField(max_length=30, verbose_name='Type of Location')),
                ('address', models.CharField(max_length=30, verbose_name='Address of Location')),
                ('lat_coord', models.DecimalField(decimal_places=6, default=40.002287, max_digits=9)),
                ('long_coord', models.DecimalField(decimal_places=6, default=-83.016017, max_digits=9)),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name='Business Phone Number')),
                ('price', models.CharField(blank=True, choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], max_length=1, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(verbose_name='start time of event')),
                ('end_time', models.TimeField(verbose_name='end time of event')),
                ('show', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.Plan')),
            ],
        ),
    ]
