# Generated by Django 2.2.5 on 2019-12-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='address',
            field=models.CharField(default='downtown columbus', max_length=100, verbose_name='Where would you like to search?'),
            preserve_default=False,
        ),
    ]
