# Generated by Django 2.2.5 on 2019-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='plan',
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Business Phone Number'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Address of Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='loc_name',
            field=models.CharField(max_length=30, verbose_name='Name of Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='loc_type',
            field=models.CharField(max_length=30, verbose_name='Type of Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
