# Generated by Django 2.1.4 on 2019-11-29 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Where would you like to search?')),
                ('loc_type', models.CharField(blank=True, choices=[('restaurants', 'restaurants'), ('bars', 'bars'), ('arts & entertainment', 'arts & entertainment')], max_length=100, null=True, verbose_name='Location Type')),
                ('loc_category', models.CharField(blank=True, choices=[('0', '--------'), ('1', 'empty')], max_length=100, null=True, verbose_name='Location Category')),
                ('price', models.CharField(blank=True, choices=[('', 'Choose a price level'), ('1', '$'), ('2', '$$'), ('3', '$$$')], default='', max_length=1, null=True)),
                ('min_rating', models.CharField(blank=True, choices=[('', 'Choose a minimum rating'), ('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], max_length=1, null=True, verbose_name='Minimum Rating')),
                ('transportation', models.CharField(blank=True, choices=[('1', 'Walk'), ('2', 'Car'), ('3', 'Both')], max_length=1, null=True, verbose_name='Mode of Transportation')),
                ('result_count', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Number of Search Results')),
                ('start_time', models.TimeField(blank=True, default='12:00', null=True, verbose_name='Start Time of Event')),
                ('end_time', models.TimeField(blank=True, default='12:30', null=True, verbose_name='End Time of Event')),
                ('search_radius', models.FloatField(default=5, verbose_name='Search Radius(in miles)')),
                ('lat_coord', models.DecimalField(decimal_places=6, default=40.002287, max_digits=9)),
                ('long_coord', models.DecimalField(decimal_places=6, default=-83.016017, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='plan',
        ),
        migrations.AddField(
            model_name='event',
            name='lat_coord',
            field=models.DecimalField(decimal_places=6, default=40.002287, max_digits=9),
        ),
        migrations.AddField(
            model_name='event',
            name='long_coord',
            field=models.DecimalField(decimal_places=6, default=-83.016017, max_digits=9),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Business Phone Number'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Address of Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='end time of event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='loc_name',
            field=models.CharField(max_length=30, verbose_name='Name of Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='loc_type',
            field=models.CharField(max_length=30, verbose_name='Type of Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='start time of event'),
        ),
    ]
