# Generated by Django 2.2.5 on 2019-11-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20191127_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time of Event'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location Category'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time of Event'),
        ),
    ]
