# Generated by Django 2.2.5 on 2019-12-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20191202_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_type',
            field=models.CharField(choices=[('restaurants', 'Restaurants'), ('bars', 'Bars'), ('arts & entertainment', 'Arts & Entertainment')], max_length=100, verbose_name='Location Type'),
        ),
    ]
