# Generated by Django 2.2.5 on 2019-12-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20191202_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='price',
            field=models.CharField(blank=True, choices=[('', 'Choose a price level'), ('1', '$'), ('2', '$$'), ('3', '$$$')], default='', max_length=1),
        ),
    ]
