# Generated by Django 2.1.4 on 2019-11-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20191129_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPlan',
        ),
    ]
