# Generated by Django 2.2.5 on 2019-11-28 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20191127_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='End Time of Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_type',
            field=models.CharField(choices=[('restaurants', 'restaurants'), ('bars', 'bars'), ('arts & entertainment', 'arts & entertainment')], default='restaurants', max_length=100, verbose_name='Location Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Start Time of Event'),
            preserve_default=False,
        ),
    ]
