# Generated by Django 2.2.5 on 2019-09-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20190926_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_type', models.CharField(choices=[('1', 'Mexican Food'), ('2', 'Ice Cream'), ('3', 'Coffee Shop'), ('3', 'Seafood'), ('3', 'Other Restaurants')], max_length=1, verbose_name='Location Type')),
                ('price', models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], max_length=1)),
                ('size', models.CharField(choices=[('1', '1'), ('2', '2-3'), ('3', '4+')], max_length=1, verbose_name='Group Size')),
                ('transportation', models.CharField(choices=[('1', 'Walk'), ('2', 'Car'), ('3', 'Both')], max_length=1, verbose_name='Mode of Transportation')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], max_length=1, null=True),
        ),
    ]
