# Generated by Django 2.2.5 on 2019-12-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20191127_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=80, verbose_name='Address of Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='loc_name',
            field=models.CharField(max_length=50, verbose_name='Name of Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='loc_type',
            field=models.CharField(max_length=50, verbose_name='Type of Location'),
        ),
    ]
