# Generated by Django 2.1.4 on 2019-11-29 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20191129_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date planned'),
        ),
    ]
