# Generated by Django 2.2.5 on 2019-10-16 02:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20190926_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.Event')),
                ('chosen', models.IntegerField(default=0, max_length=1)),
            ],
            bases=('planner.event',),
        ),
        migrations.AddField(
            model_name='eventfinder',
            name='result_count',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_type',
            field=models.CharField(choices=[('1', 'Mexican'), ('2', 'Ice Cream'), ('3', 'Coffee Shop'), ('4', 'Seafood'), ('5', 'Other Restaurants')], max_length=1, verbose_name='Location Type'),
        ),
    ]
