# Generated by Django 2.2.5 on 2019-12-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20191201_1921'),
        ('planner', '0006_auto_20191129_1609'),
    ]

    operations = [
    ]
