# Generated by Django 2.2.5 on 2019-10-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20191015_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time of event'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_type',
            field=models.CharField(blank=True, choices=[('1', 'Mexican'), ('2', 'Ice Cream'), ('3', 'Coffee Shop'), ('4', 'Seafood'), ('5', 'Other Restaurants')], max_length=1, null=True, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='price',
            field=models.CharField(blank=True, choices=[('1', '$'), ('2', '$$'), ('3', '$$$')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='size',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2-3'), ('3', '4+')], max_length=1, null=True, verbose_name='Group Size'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time of event'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='transportation',
            field=models.CharField(blank=True, choices=[('1', 'Walk'), ('2', 'Car'), ('3', 'Both')], max_length=1, null=True, verbose_name='Mode of Transportation'),
        ),
    ]
