# Generated by Django 2.2.5 on 2019-12-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_merge_20191201_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='search_radius',
            field=models.FloatField(blank=True, default=10, null=True, verbose_name='Max Distance Away (in miles)'),
        ),
    ]
