# Generated by Django 2.2.5 on 2019-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20191016_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='end_time',
            field=models.TimeField(blank=True, default='12:30', null=True, verbose_name='end time of event'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='start_time',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='start time of event'),
        ),
    ]
