# Generated by Django 2.2.5 on 2019-10-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20191016_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventfinder',
            name='size',
        ),
        migrations.AddField(
            model_name='event',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventfinder',
            name='min_rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True, verbose_name='Group Size'),
        ),
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
