# Generated by Django 2.2.6 on 2019-10-29 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20191016_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='end_time',
            field=models.TimeField(blank=True, default='12:30', null=True, verbose_name='End Time of Event'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_type',
            field=models.CharField(blank=True, choices=[('American (New)', 'American (New)'), ('American (Traditional)', 'American (Traditional)'), ('Aquariums', 'Aquariums'), ('Bakeries', 'Bakeries'), ('Barbeque', 'Barbeque'), ('Bars', 'Bars'), ('Beer Bar', 'Beer Bar'), ('Bookstores', 'Bookstores'), ('Breakfast & Brunch', 'Breakfast & Brunch'), ('Bubble Tea', 'Bubble Tea'), ('Burgers', 'Burgers'), ('Cafes', 'Cafes'), ('Cajun/Creole', 'Cajun/Creole'), ('Chicken Shop', 'Chicken Shop'), ('Coffee & Tea', 'Coffee & Tea'), ('Comfort Food', 'Comfort Food'), ('Custom Cakes', 'Custom Cakes'), ('Delis', 'Delis'), ('Desserts', 'Desserts'), ('Donuts', 'Donuts'), ('Ethiopian', 'Ethiopian'), ('Food Trucks', 'Food Trucks'), ('Gelato', 'Gelato'), ('German', 'German'), ('Gluten-Free', 'Gluten-Free'), ('Greek', 'Greek'), ('Hawaiian', 'Hawaiian'), ('Himalayan/Nepalese', 'Himalayan/Nepalese'), ('Ice Cream & Frozen Yogurt', 'Ice Cream & Frozen Yogurt'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('Middle Eastern', 'Middle Eastern'), ('Peruvian', 'Peruvian'), ('Pizza', 'Pizza'), ('Poke', 'Poke'), ('Pubs', 'Pubs'), ('Salad', 'Salad'), ('Sandwiches', 'Sandwiches'), ('Seafood', 'Seafood'), ('Seafood Markets', 'Seafood Markets'), ('Soul Food', 'Soul Food'), ('Soup', 'Soup'), ('Southern', 'Southern'), ('Tacos', 'Tacos'), ('Tea Rooms', 'Tea Rooms'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Zoos', 'Zoos')], max_length=100, null=True, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='min_rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True, verbose_name='Minimum Rating (out of 5)'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='result_count',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Number of Search Results'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='start_time',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='Start Time of Event'),
        ),
    ]
