# Generated by Django 2.2.5 on 2019-11-12 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20191016_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat_coord',
            field=models.DecimalField(decimal_places=6, default=40.002287, max_digits=9),
        ),
        migrations.AddField(
            model_name='event',
            name='long_coord',
            field=models.DecimalField(decimal_places=6, default=-83.016017, max_digits=9),
        ),
        migrations.AddField(
            model_name='eventfinder',
            name='lat_coord',
            field=models.DecimalField(decimal_places=6, default=40.002287, max_digits=9),
        ),
        migrations.AddField(
            model_name='eventfinder',
            name='long_coord',
            field=models.DecimalField(decimal_places=6, default=-83.016017, max_digits=9),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='end_time',
            field=models.TimeField(blank=True, default='12:30', null=True, verbose_name='End Time of Event'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_type',
            field=models.CharField(blank=True, choices=[('Acai Bowls', 'Acai Bowls'), ('Afghan', 'Afghan'), ('African', 'African'), ('American (New)', 'American (New)'), ('American (Traditional)', 'American (Traditional)'), ('Arcades', 'Arcades'), ('Argentine', 'Argentine'), ('Asian Fusion', 'Asian Fusion'), ('Bagels', 'Bagels'), ('Bakeries', 'Bakeries'), ('Barbeque', 'Barbeque'), ('Bars', 'Bars'), ('Beer Bar', 'Beer Bar'), ('Beer Gardens', 'Beer Gardens'), ('Beer, Wine & Spirits', 'Beer, Wine & Spirits'), ('Belgian', 'Belgian'), ('Bookstores', 'Bookstores'), ('Bowling', 'Bowling'), ('Brazilian', 'Brazilian'), ('Breakfast & Brunch', 'Breakfast & Brunch'), ('Breweries', 'Breweries'), ('Brewpubs', 'Brewpubs'), ('British', 'British'), ('Bubble Tea', 'Bubble Tea'), ('Buffets', 'Buffets'), ('Burgers', 'Burgers'), ('Cafes', 'Cafes'), ('Cafeteria', 'Cafeteria'), ('Cajun/Creole', 'Cajun/Creole'), ('Caribbean', 'Caribbean'), ('Caterers', 'Caterers'), ('Cheesesteaks', 'Cheesesteaks'), ('Chicken Shop', 'Chicken Shop'), ('Chicken Wings', 'Chicken Wings'), ('Chinese', 'Chinese'), ('Cigar Bars', 'Cigar Bars'), ('Cocktail Bars', 'Cocktail Bars'), ('Coffee & Tea', 'Coffee & Tea'), ('Coffee Roasteries', 'Coffee Roasteries'), ('Comedy Clubs', 'Comedy Clubs'), ('Comfort Food', 'Comfort Food'), ('Cooking Classes', 'Cooking Classes'), ('Creperies', 'Creperies'), ('Cuban', 'Cuban'), ('Cupcakes', 'Cupcakes'), ('Custom Cakes', 'Custom Cakes'), ('Dance Clubs', 'Dance Clubs'), ('Delis', 'Delis'), ('Desserts', 'Desserts'), ('Diners', 'Diners'), ('Dinner Theater', 'Dinner Theater'), ('Dive Bars', 'Dive Bars'), ('Dominican', 'Dominican'), ('Donuts', 'Donuts'), ('Egyptian', 'Egyptian'), ('Empanadas', 'Empanadas'), ('Ethiopian', 'Ethiopian'), ('Falafel', 'Falafel'), ('Fast Food', 'Fast Food'), ('Festivals', 'Festivals'), ('Filipino', 'Filipino'), ('Fish & Chips', 'Fish & Chips'), ('Fondue', 'Fondue'), ('Food Stands', 'Food Stands'), ('Food Trucks', 'Food Trucks'), ('French', 'French'), ('Gastropubs', 'Gastropubs'), ('Gay Bars', 'Gay Bars'), ('German', 'German'), ('Gluten-Free', 'Gluten-Free'), ('Greek', 'Greek'), ('Grocery', 'Grocery'), ('Haitian', 'Haitian'), ('Halal', 'Halal'), ('Hawaiian', 'Hawaiian'), ('Health Markets', 'Health Markets'), ('Himalayan/Nepalese', 'Himalayan/Nepalese'), ('Hookah Bars', 'Hookah Bars'), ('Hot Dogs', 'Hot Dogs'), ('Hot Pot', 'Hot Pot'), ('Ice Cream & Frozen Yogurt', 'Ice Cream & Frozen Yogurt'), ('Imported Food', 'Imported Food'), ('Indian', 'Indian'), ('International Grocery', 'International Grocery'), ('Irish', 'Irish'), ('Irish Pub', 'Irish Pub'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Jazz & Blues', 'Jazz & Blues'), ('Juice Bars & Smoothies', 'Juice Bars & Smoothies'), ('Karaoke', 'Karaoke'), ('Kids Activities', 'Kids Activities'), ('Korean', 'Korean'), ('Laotian', 'Laotian'), ('Laser Tag', 'Laser Tag'), ('Latin American', 'Latin American'), ('Lebanese', 'Lebanese'), ('Local Flavor', 'Local Flavor'), ('Lounges', 'Lounges'), ('Macarons', 'Macarons'), ('Meat Shops', 'Meat Shops'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('Middle Eastern', 'Middle Eastern'), ('Modern European', 'Modern European'), ('Mongolian', 'Mongolian'), ('Moroccan', 'Moroccan'), ('Music Venues', 'Music Venues'), ('Noodles', 'Noodles'), ('Pakistani', 'Pakistani'), ('Party & Event Planning', 'Party & Event Planning'), ('Pasta Shops', 'Pasta Shops'), ('Persian/Iranian', 'Persian/Iranian'), ('Peruvian', 'Peruvian'), ('Pet Adoption', 'Pet Adoption'), ('Pizza', 'Pizza'), ('Poke', 'Poke'), ('Polish', 'Polish'), ('Pool Halls', 'Pool Halls'), ('Pop-Up Restaurants', 'Pop-Up Restaurants'), ('Pretzels', 'Pretzels'), ('Pubs', 'Pubs'), ('Puerto Rican', 'Puerto Rican'), ('Ramen', 'Ramen'), ('Restaurants', 'Restaurants'), ('Russian', 'Russian'), ('Salad', 'Salad'), ('Salvadoran', 'Salvadoran'), ('Sandwiches', 'Sandwiches'), ('Seafood', 'Seafood'), ('Seafood Markets', 'Seafood Markets'), ('Senegalese', 'Senegalese'), ('Smokehouse', 'Smokehouse'), ('Somali', 'Somali'), ('Soul Food', 'Soul Food'), ('Soup', 'Soup'), ('South African', 'South African'), ('Southern', 'Southern'), ('Spanish', 'Spanish'), ('Specialty Food', 'Specialty Food'), ('Sports Bars', 'Sports Bars'), ('Steakhouses', 'Steakhouses'), ('Street Vendors', 'Street Vendors'), ('Sushi Bars', 'Sushi Bars'), ('Szechuan', 'Szechuan'), ('Tabletop Games', 'Tabletop Games'), ('Tacos', 'Tacos'), ('Taiwanese', 'Taiwanese'), ('Tapas Bars', 'Tapas Bars'), ('Tapas/Small Plates', 'Tapas/Small Plates'), ('Tex-Mex', 'Tex-Mex'), ('Thai', 'Thai'), ('Themed Cafes', 'Themed Cafes'), ('Trinidadian', 'Trinidadian'), ('Turkish', 'Turkish'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Venezuelan', 'Venezuelan'), ('Venues & Event Spaces', 'Venues & Event Spaces'), ('Vietnamese', 'Vietnamese'), ('Waffles', 'Waffles'), ('Whiskey Bars', 'Whiskey Bars'), ('Wine Bars', 'Wine Bars'), ('Wine Tasting Room', 'Wine Tasting Room'), ('Wraps', 'Wraps')], max_length=100, null=True, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='min_rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True, verbose_name='Minimum Rating (out of 5)'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='result_count',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Number of Search Results'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='start_time',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='Start Time of Event'),
        ),
    ]
