# Generated by Django 2.2.5 on 2019-11-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20191112_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfinder',
            name='search_radius',
            field=models.FloatField(default=5, verbose_name='Search Radius(in miles)'),
        ),
    ]
