# Generated by Django 2.2.5 on 2019-11-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20191027_1450'),
        ('planner', '0012_eventfinder_search_radius'),
    ]

    operations = [
    ]
