# Generated by Django 2.2.6 on 2019-11-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20191114_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planner.Plan'),
        ),
    ]
