# Generated by Django 2.2.6 on 2019-11-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_auto_20191114_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='plan',
        ),
        migrations.AddField(
            model_name='event',
            name='plan_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Plan'),
        ),
    ]
