# Generated by Django 2.2.5 on 2019-11-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_auto_20191119_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfinder',
            name='loc_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location Ctegory'),
        ),
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_type',
            field=models.CharField(blank=True, choices=[('restaurants', 'restaurants'), ('bars', 'bars'), ('arts & entertainment', 'arts & entertainment')], max_length=100, null=True, verbose_name='Location Type'),
        ),
    ]
