# Generated by Django 2.2.6 on 2019-11-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20191114_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.Plan'),
        ),
    ]
