# Generated by Django 2.2.5 on 2019-11-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20191121_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinder',
            name='loc_category',
            field=models.CharField(blank=True, choices=[('0', '--------'), ('1', 'empty')], max_length=100, null=True, verbose_name='Location Category'),
        ),
    ]
