# Generated by Django 2.2.6 on 2019-11-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_auto_20191114_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
